CALL InsertStadium('ST_ABD', 'ABD', 'Pittodrie Stadium', 20866, 'Aberdeen, Scotland');
CALL InsertStadium('ST_AJA', 'AJA', 'Johan Cruyff Arena', 55000, 'Amsterdam, Netherlands');
CALL InsertStadium('ST_AST', 'AST', 'Villa Park', 42657, 'Birmingham, England');
CALL InsertStadium('ST_ATH', 'ATH', 'San Mamés', 53289, 'Bilbao, Spain');
CALL InsertStadium('ST_ATM', 'ATM', 'Wanda Metropolitano', 68456, 'Madrid, Spain');
CALL InsertStadium('ST_AVE', 'AVE', 'Estádio do Clube Desportivo', 8500, 'Vila das Aves, Portugal');
CALL InsertStadium('ST_AZA', 'AZA', 'AFAS Stadion', 17000, 'Alkmaar, Netherlands');
CALL InsertStadium('ST_BAR', 'BAR', 'Camp Nou', 99354, 'Barcelona, Spain');
CALL InsertStadium('ST_BAY', 'BAY', 'Allianz Arena', 75000, 'Munich, Germany');
CALL InsertStadium('ST_BEL', 'BEL', 'Estádio do Restelo', 19856, 'Lisbon, Portugal');
CALL InsertStadium('ST_BEN', 'BEN', 'Estádio da Luz', 64642, 'Lisbon, Portugal');
CALL InsertStadium('ST_BET', 'BET', 'Benito Villamarín', 60720, 'Seville, Spain');
CALL InsertStadium('ST_BOA', 'BOA', 'Estádio do Bessa', 28263, 'Porto, Portugal');
CALL InsertStadium('ST_BOR', 'BOR', 'Matmut Atlantique', 42115, 'Bordeaux, France');
CALL InsertStadium('ST_BRA', 'BRA', 'Estádio Municipal de Braga', 30286, 'Braga, Portugal');
CALL InsertStadium('ST_CEL', 'CEL', 'Celtic Park', 60411, 'Glasgow, Scotland');
CALL InsertStadium('ST_CHE', 'CHE', 'Stamford Bridge', 40341, 'London, England');
CALL InsertStadium('ST_DOR', 'DOR', 'Signal Iduna Park', 81365, 'Dortmund, Germany');
CALL InsertStadium('ST_DUN', 'DUN', 'Tannadice Park', 14223, 'Dundee, Scotland');
CALL InsertStadium('ST_ESP', 'ESP', 'RCDE Stadium', 40500, 'Barcelona, Spain');
CALL InsertStadium('ST_EVE', 'EVE', 'Goodison Park', 39414, 'Liverpool, England');
CALL InsertStadium('ST_FER', 'FER', 'Estádio Municipal de Famalicão', 5282, 'Famalicão, Portugal');
CALL InsertStadium('ST_FEY', 'FEY', 'De Kuip', 51177, 'Rotterdam, Netherlands');
CALL InsertStadium('ST_FIO', 'FIO', 'Stadio Artemio Franchi', 43147, 'Florence, Italy');
CALL InsertStadium('ST_FRE', 'FRE', 'Europa-Park Stadion', 34700, 'Freiburg, Germany');
CALL InsertStadium('ST_GEN', 'GEN', 'Stadio Luigi Ferraris', 36599, 'Genoa, Italy');
CALL InsertStadium('ST_GRO', 'GRO', 'Euroborg', 22579, 'Groningen, Netherlands');
CALL InsertStadium('ST_GUI', 'GUI', 'Estádio D. Afonso Henriques', 30000, 'Guimarães, Portugal');
CALL InsertStadium('ST_HEA', 'HEA', 'Tynecastle Park', 19852, 'Edinburgh, Scotland');
CALL InsertStadium('ST_HEE', 'HEE', 'Abe Lenstra Stadion', 27000, 'Heerenveen, Netherlands');
CALL InsertStadium('ST_HER', 'HER', 'Olympiastadion Berlin', 74475, 'Berlin, Germany');
CALL InsertStadium('ST_HIB', 'HIB', 'Easter Road', 20421, 'Edinburgh, Scotland');
CALL InsertStadium('ST_INT', 'INT', 'San Siro', 80018, 'Milan, Italy');
CALL InsertStadium('ST_JUV', 'JUV', 'Allianz Stadium', 41507, 'Turin, Italy');
CALL InsertStadium('ST_KIL', 'KIL', 'Rugby Park', 17989, 'Kilmarnock, Scotland');
CALL InsertStadium('ST_LAZ', 'LAZ', 'Stadio Olimpico', 70634, 'Rome, Italy');
CALL InsertStadium('ST_LEI', 'LEI', 'King Power Stadium', 32312, 'Leicester, England');
CALL InsertStadium('ST_LEV', 'LEV', 'BayArena', 30210, 'Leverkusen, Germany');
CALL InsertStadium('ST_LIL', 'LIL', 'Stade Pierre-Mauroy', 50000, 'Lille, France');
CALL InsertStadium('ST_LIV', 'LIV', 'Anfield', 54074, 'Liverpool, England');
CALL InsertStadium('ST_LIVI', 'LIVI', 'Tony Macaroni Arena', 9324, 'Livingston, Scotland');
CALL InsertStadium('ST_LYO', 'LYO', 'Groupama Stadium', 59186, 'Lyon, France');
CALL InsertStadium('ST_MAR', 'MAR', 'Stade Vélodrome', 67394, 'Marseille, France');
CALL InsertStadium('ST_MCFC', 'MCFC', 'Etihad Stadium', 53400, 'Manchester, England');
CALL InsertStadium('ST_MIL', 'MIL', 'San Siro', 80018, 'Milan, Italy');
CALL InsertStadium('ST_MLG', 'MLG', 'La Rosaleda', 30044, 'Malaga, Spain');
CALL InsertStadium('ST_MOE', 'MOE', 'Borussia-Park', 54022, 'Mönchengladbach, Germany');
CALL InsertStadium('ST_MON', 'MON', 'Stade Louis II', 18523, 'Monaco, France');
CALL InsertStadium('ST_MOT', 'MOT', 'Fir Park', 13000, 'Motherwell, Scotland');
CALL InsertStadium('ST_NAP', 'NAP', 'Stadio Diego Armando Maradona', 54726, 'Naples, Italy');
CALL InsertStadium('ST_NIC', 'NIC', 'Allianz Riviera', 35624, 'Nice, France');
CALL InsertStadium('ST_POR', 'POR', 'Estádio do Dragão', 50033, 'Porto, Portugal');
CALL InsertStadium('ST_PSG', 'PSG', 'Parc des Princes', 47929, 'Paris, France');
CALL InsertStadium('ST_PSV', 'PSV', 'Philips Stadion', 35000, 'Eindhoven, Netherlands');
CALL InsertStadium('ST_RAN', 'RAN', 'Ibrox Stadium', 50817, 'Glasgow, Scotland');
CALL InsertStadium('ST_RBL', 'RBL', 'Red Bull Arena', 42959, 'Leipzig, Germany');
CALL InsertStadium('ST_REI', 'REI', 'Stade Auguste-Delaune', 21684, 'Reims, France');
CALL InsertStadium('ST_REN', 'REN', 'Roazhon Park', 29778, 'Rennes, France');
CALL InsertStadium('ST_RMD', 'RMD', 'Santiago Bernabéu', 81044, 'Madrid, Spain');
CALL InsertStadium('ST_ROM', 'ROM', 'Stadio Olimpico', 70634, 'Rome, Italy');
CALL InsertStadium('ST_RSO', 'RSO', 'Anoeta Stadium', 39000, 'San Sebastián, Spain');
CALL InsertStadium('ST_SCH', 'SCH', 'Veltins-Arena', 62271, 'Gelsenkirchen, Germany');
CALL InsertStadium('ST_SEV', 'SEV', 'Ramón Sánchez Pizjuán', 43883, 'Seville, Spain');
CALL InsertStadium('ST_SPO', 'SPO', 'Estádio José Alvalade', 50095, 'Lisbon, Portugal');
CALL InsertStadium('ST_STJ', 'STJ', 'McDiarmid Park', 10696, 'Perth, Scotland');
CALL InsertStadium('ST_STR', 'STR', 'Stade de la Meinau', 29200, 'Strasbourg, France');
CALL InsertStadium('ST_STU', 'STU', 'Mercedes-Benz Arena', 60449, 'Stuttgart, Germany');
CALL InsertStadium('ST_TOR', 'TOR', 'Stadio Olimpico Grande Torino', 27994, 'Turin, Italy');
CALL InsertStadium('ST_TOT', 'TOT', 'Tottenham Hotspur Stadium', 62850, 'London, England');
CALL InsertStadium('ST_TWE', 'TWE', 'De Grolsch Veste', 30205, 'Enschede, Netherlands');
CALL InsertStadium('ST_UDI', 'UDI', 'Stadio Friuli', 25144, 'Udine, Italy');
CALL InsertStadium('ST_UTR', 'UTR', 'Stadion Galgenwaard', 23750, 'Utrecht, Netherlands');
CALL InsertStadium('ST_VAL', 'VAL', 'Mestalla', 49000, 'Valencia, Spain');
CALL InsertStadium('ST_VIT', 'VIT', 'GelreDome', 25000, 'Arnhem, Netherlands');
CALL InsertStadium('ST_WHU', 'WHU', 'London Stadium', 62500, 'London, England');
CALL InsertStadium('ST_WIL', 'WIL', 'Koning Willem II Stadion', 14400, 'Tilburg, Netherlands');
CALL InsertStadium('ST_WOB', 'WOB', 'Volkswagen Arena', 30000, 'Wolfsburg, Germany');

SELECT * FROM stadium_t;