/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package afcmanagementsystem;

/**
 *
 * @author Ruchir Alamchand
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

public class Clubs extends javax.swing.JFrame {

    /**
     * Creates new form Clubs
     */
    public Clubs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClubsPanel = new javax.swing.JPanel();
        BorderPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        AddingBorder = new javax.swing.JPanel();
        ClubLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        CountryLabel = new javax.swing.JLabel();
        FoundingYearLabel = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        ClubTF = new javax.swing.JTextField();
        CountryTF = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        ShowBtn = new javax.swing.JButton();
        FoundingYearTF = new javax.swing.JTextField();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClubTbl = new javax.swing.JTable();
        BorderPanel1 = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        AddingBorder1 = new javax.swing.JPanel();
        ClubLabel1 = new javax.swing.JLabel();
        NameLabel1 = new javax.swing.JLabel();
        CountryLabel1 = new javax.swing.JLabel();
        DateOfBirthLabel = new javax.swing.JLabel();
        PresNameTF = new javax.swing.JTextField();
        PresIDTF = new javax.swing.JTextField();
        PresCountryTF = new javax.swing.JTextField();
        NameLabel2 = new javax.swing.JLabel();
        PresSurnameTF = new javax.swing.JTextField();
        PresClubIDLabel = new javax.swing.JLabel();
        PresClubIDTF = new javax.swing.JTextField();
        PresCalendar = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        PresTbl = new javax.swing.JTable();
        PresAddBtn = new javax.swing.JButton();
        PresUpDateBtn = new javax.swing.JButton();
        PresDeleteBtn = new javax.swing.JButton();
        PresShowBtn = new javax.swing.JButton();
        PresClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ClubsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ClubsPanel.setBorder(new javax.swing.border.MatteBorder(null));

        BorderPanel.setBackground(new java.awt.Color(255, 255, 255));
        BorderPanel.setBorder(new javax.swing.border.MatteBorder(null));

        Title.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        Title.setText("CLUBS OVERVIEW");

        javax.swing.GroupLayout BorderPanelLayout = new javax.swing.GroupLayout(BorderPanel);
        BorderPanel.setLayout(BorderPanelLayout);
        BorderPanelLayout.setHorizontalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BorderPanelLayout.setVerticalGroup(
            BorderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddingBorder.setBackground(new java.awt.Color(255, 255, 255));
        AddingBorder.setBorder(new javax.swing.border.MatteBorder(null));

        ClubLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        ClubLabel.setText("Club ID:");

        NameLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        NameLabel.setText("Name:");

        CountryLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        CountryLabel.setText("Country:");

        FoundingYearLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        FoundingYearLabel.setText("Founding Year:");

        NameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTFActionPerformed(evt);
            }
        });

        ClubTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClubTFActionPerformed(evt);
            }
        });

        CountryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryTFActionPerformed(evt);
            }
        });

        AddBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        AddBtn.setText("ADD");
        AddBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        UpdateBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        UpdateBtn.setText("UPDATE");
        UpdateBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        DeleteBtn.setText("DELETE");
        DeleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        ShowBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        ShowBtn.setText("SHOW");
        ShowBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBtnActionPerformed(evt);
            }
        });

        FoundingYearTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoundingYearTFActionPerformed(evt);
            }
        });

        ClearBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        ClearBtn.setText("CLEAR");
        ClearBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddingBorderLayout = new javax.swing.GroupLayout(AddingBorder);
        AddingBorder.setLayout(AddingBorderLayout);
        AddingBorderLayout.setHorizontalGroup(
            AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddingBorderLayout.createSequentialGroup()
                        .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FoundingYearLabel)
                            .addComponent(CountryLabel)
                            .addComponent(NameLabel)
                            .addComponent(ClubLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClubTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FoundingYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddingBorderLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddingBorderLayout.createSequentialGroup()
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddingBorderLayout.createSequentialGroup()
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddingBorderLayout.setVerticalGroup(
            AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClubLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClubTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FoundingYearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoundingYearTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(212, 212, 212))
        );

        ClubTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Club ID", "Name", "Surname", "Founding Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ClubTbl);

        BorderPanel1.setBackground(new java.awt.Color(255, 255, 255));
        BorderPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        Title1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 48)); // NOI18N
        Title1.setText("PRESIDENTS");

        javax.swing.GroupLayout BorderPanel1Layout = new javax.swing.GroupLayout(BorderPanel1);
        BorderPanel1.setLayout(BorderPanel1Layout);
        BorderPanel1Layout.setHorizontalGroup(
            BorderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(Title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BorderPanel1Layout.setVerticalGroup(
            BorderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorderPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Title1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddingBorder1.setBackground(new java.awt.Color(255, 255, 255));
        AddingBorder1.setBorder(new javax.swing.border.MatteBorder(null));

        ClubLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        ClubLabel1.setText("Pres ID");

        NameLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        NameLabel1.setText("Name:");

        CountryLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        CountryLabel1.setText("Country:");

        DateOfBirthLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        DateOfBirthLabel.setText("Date Of Birth:");

        PresNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresNameTFActionPerformed(evt);
            }
        });

        PresIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresIDTFActionPerformed(evt);
            }
        });

        PresCountryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresCountryTFActionPerformed(evt);
            }
        });

        NameLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        NameLabel2.setText("Surname:");

        PresSurnameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresSurnameTFActionPerformed(evt);
            }
        });

        PresClubIDLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresClubIDLabel.setText("Club ID:");

        PresClubIDTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresClubIDTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddingBorder1Layout = new javax.swing.GroupLayout(AddingBorder1);
        AddingBorder1.setLayout(AddingBorder1Layout);
        AddingBorder1Layout.setHorizontalGroup(
            AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingBorder1Layout.createSequentialGroup()
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddingBorder1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CountryLabel1)
                            .addComponent(NameLabel1)
                            .addComponent(ClubLabel1)
                            .addComponent(NameLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddingBorder1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PresClubIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateOfBirthLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PresNameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(PresIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(PresCountryTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(PresSurnameTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(PresClubIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(PresCalendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        AddingBorder1Layout.setVerticalGroup(
            AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddingBorder1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClubLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PresNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresSurnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountryLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresCountryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DateOfBirthLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddingBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PresClubIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddingBorder1Layout.createSequentialGroup()
                        .addComponent(PresClubIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(229, 229, 229))
        );

        PresTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pres ID", "Name", "Surname", "Country", "DateOfBirth", "ClubID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(PresTbl);

        PresAddBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresAddBtn.setText("ADD");
        PresAddBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PresAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresAddBtnActionPerformed(evt);
            }
        });

        PresUpDateBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresUpDateBtn.setText("UPDATE");
        PresUpDateBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PresUpDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresUpDateBtnActionPerformed(evt);
            }
        });

        PresDeleteBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresDeleteBtn.setText("DELETE");
        PresDeleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PresDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresDeleteBtnActionPerformed(evt);
            }
        });

        PresShowBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresShowBtn.setText("SHOW");
        PresShowBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PresShowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresShowBtnActionPerformed(evt);
            }
        });

        PresClearBtn.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        PresClearBtn.setText("CLEAR");
        PresClearBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PresClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PresClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClubsPanelLayout = new javax.swing.GroupLayout(ClubsPanel);
        ClubsPanel.setLayout(ClubsPanelLayout);
        ClubsPanelLayout.setHorizontalGroup(
            ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BorderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ClubsPanelLayout.createSequentialGroup()
                .addGroup(ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClubsPanelLayout.createSequentialGroup()
                        .addComponent(AddingBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BorderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ClubsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddingBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(ClubsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PresAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PresDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PresUpDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PresShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PresClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ClubsPanelLayout.setVerticalGroup(
            ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClubsPanelLayout.createSequentialGroup()
                .addComponent(BorderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddingBorder, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BorderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddingBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClubsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PresAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresUpDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresShowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PresClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(401, 401, 401))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClubsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ClubsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTFActionPerformed

    private void ClubTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClubTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClubTFActionPerformed

    private void CountryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryTFActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

    
    String clubID = ClubTF.getText();           
    String clubName = NameTF.getText();      
    String country = CountryTF.getText();          
    int foundingYear = Integer.parseInt(FoundingYearTF.getText()); 

    // Use PreparedStatement for safe insertion
    String sql = "INSERT INTO FOOTBALLCLUB (ClubID, ClubName, Country, FoundingYear) VALUES (?, ?, ?, ?)";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, clubID);
    pst.setString(2, clubName);
    pst.setString(3, country);
    pst.setInt(4, foundingYear);

    // Execute insert
    int rowsInserted = pst.executeUpdate();
    if (rowsInserted > 0) {
        JOptionPane.showMessageDialog(null, "Club added successfully!");
    }

    con.close();
} catch (Exception e) {
    System.out.println(e.getMessage());
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_AddBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
     try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

        String clubID = ClubTF.getText();              
        String newName = NameTF.getText();           
        String newCountry = CountryTF.getText();         
        int newFoundingYear = Integer.parseInt(FoundingYearTF.getText());  

        // Create and execute update statement
        String sql = "UPDATE FOOTBALLCLUB SET ClubName = ?, Country = ?, FoundingYear = ? WHERE ClubID = ?";
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setString(1, newName);
        statement.setString(2, newCountry);
        statement.setInt(3, newFoundingYear);
        statement.setString(4, clubID);

        int rowsUpdated = statement.executeUpdate();
        if (rowsUpdated > 0) {
            JOptionPane.showMessageDialog(null, "Club updated successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Club not found.");
        }

        con.close();
    } catch (Exception e) {
        System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
  
    }//GEN-LAST:event_UpdateBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

            String clubID = ClubTF.getText();

            String sql = "DELETE FROM FOOTBALLCLUB WHERE ClubID = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, clubID);

            int rowsDeleted = pst.executeUpdate();
            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(null, "Club deleted successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Club ID not found.");
            }
            DefaultTableModel tblModel = (DefaultTableModel)ClubTbl.getModel();
            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void ShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBtnActionPerformed
        try{
            DefaultTableModel tblModel = (DefaultTableModel)ClubTbl.getModel();
            tblModel.setRowCount(0);//clear the table
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement","root","Alamchand@123");
            Statement st = con.createStatement();
            
            String sql = "SELECT * FROM FOOTBALLCLUB";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String id = rs.getString("ClubID");
                String name = rs.getString("ClubName");
                String country = rs.getString("Country");
                String FoundingY = String.valueOf(rs.getInt("FoundingYear"));
                
                String tbData [] = {id,name,country,FoundingY};
                tblModel.addRow(tbData);
            }
            
            con.close();
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ShowBtnActionPerformed

    private void FoundingYearTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoundingYearTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoundingYearTFActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        CountryTF.setText("");
        NameTF.setText("");
        ClubTF.setText("");
        FoundingYearTF.setText("");
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void PresNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresNameTFActionPerformed

    private void PresIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresIDTFActionPerformed

    private void PresCountryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresCountryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresCountryTFActionPerformed

    private void PresAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresAddBtnActionPerformed
try {
            String presID = PresIDTF.getText();
            String name = PresNameTF.getText();
            String surname = PresSurnameTF.getText();
            String country = PresCountryTF.getText();
            java.util.Date utilDate = PresCalendar.getDate();
            java.sql.Date dob = new java.sql.Date(utilDate.getTime());
            String clubID = PresClubIDTF.getText();

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

            String sql = "CALL addNewPresident(?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, presID);
            pst.setString(2, name);
            pst.setString(3, surname);
            pst.setString(4, country);
            pst.setDate(5, dob);
            pst.setString(6, clubID);

            pst.execute();

            JOptionPane.showMessageDialog(null, "President added successfully!");

            // Refresh table
            DefaultTableModel tblModel = (DefaultTableModel) PresTbl.getModel();
            tblModel.setRowCount(0); // Clear existing data
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM PRESIDENT");
            while (rs.next()) {
                String[] row = {
                    rs.getString("PresIDNumber"),
                    rs.getString("Name"),
                    rs.getString("Surname"),
                    rs.getString("CountryOfOrgin"),
                    rs.getString("DateOfBirth"),
                    rs.getString("ClubID")
                };
                tblModel.addRow(row);
            }

            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_PresAddBtnActionPerformed

    private void PresUpDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresUpDateBtnActionPerformed
try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

    String presID = PresIDTF.getText();
    String name = PresNameTF.getText();
    String surname = PresSurnameTF.getText();
    String country = PresCountryTF.getText();
    java.util.Date utilDate = PresCalendar.getDate();
    java.sql.Date dob = new java.sql.Date(utilDate.getTime());
    String clubID = PresClubIDTF.getText();

    String sql = "UPDATE PRESIDENT SET PresIDNumber = ?, Name = ?, Surname = ?, CountryOfOrgin =?, DateOfBirth =? WHERE ClubID = ?";
    PreparedStatement statement = con.prepareStatement(sql);
    statement.setString(1, presID);
    statement.setString(2, name);
    statement.setString(3, surname);
    statement.setString(4, country);
    statement.setDate(5, dob);
    statement.setString(6, clubID);

    int rowsUpdated = statement.executeUpdate();
    if (rowsUpdated > 0) {
        JOptionPane.showMessageDialog(null, "Club updated successfully!");
    } else {
        JOptionPane.showMessageDialog(null, "Club not found.");
    }

    con.close();
} catch (Exception e) {
    System.out.println(e.getMessage());
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}
    }//GEN-LAST:event_PresUpDateBtnActionPerformed

    private void PresDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresDeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresDeleteBtnActionPerformed

    private void PresShowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresShowBtnActionPerformed
try {
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/AFCManagement", "root", "Alamchand@123");

    String sql = "SELECT * FROM PRESIDENT";
    PreparedStatement pst = con.prepareStatement(sql);
    ResultSet rs = pst.executeQuery();

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[] {"PresIDNumber", "Name", "Surname", "CountryOfOrgin", "DateOfBirth", "ClubID"});

    while (rs.next()) {
        String[] row = {
            rs.getString("PresIDNumber"),
            rs.getString("Name"),
            rs.getString("Surname"),
            rs.getString("CountryOfOrgin"),
            rs.getString("DateOfBirth"),
            rs.getString("ClubID")
        };
        model.addRow(row);
    }

    PresTbl.setModel(model); 

    con.close();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_PresShowBtnActionPerformed

    private void PresClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresClearBtnActionPerformed

    private void PresSurnameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresSurnameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresSurnameTFActionPerformed

    private void PresClubIDTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PresClubIDTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PresClubIDTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clubs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clubs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JPanel AddingBorder;
    private javax.swing.JPanel AddingBorder1;
    private javax.swing.JPanel BorderPanel;
    private javax.swing.JPanel BorderPanel1;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JLabel ClubLabel;
    private javax.swing.JLabel ClubLabel1;
    private javax.swing.JTextField ClubTF;
    private javax.swing.JTable ClubTbl;
    private javax.swing.JPanel ClubsPanel;
    private javax.swing.JLabel CountryLabel;
    private javax.swing.JLabel CountryLabel1;
    private javax.swing.JTextField CountryTF;
    private javax.swing.JLabel DateOfBirthLabel;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JLabel FoundingYearLabel;
    private javax.swing.JTextField FoundingYearTF;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameLabel1;
    private javax.swing.JLabel NameLabel2;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton PresAddBtn;
    private com.toedter.calendar.JDateChooser PresCalendar;
    private javax.swing.JButton PresClearBtn;
    private javax.swing.JLabel PresClubIDLabel;
    private javax.swing.JTextField PresClubIDTF;
    private javax.swing.JTextField PresCountryTF;
    private javax.swing.JButton PresDeleteBtn;
    private javax.swing.JTextField PresIDTF;
    private javax.swing.JTextField PresNameTF;
    private javax.swing.JButton PresShowBtn;
    private javax.swing.JTextField PresSurnameTF;
    private javax.swing.JTable PresTbl;
    private javax.swing.JButton PresUpDateBtn;
    private javax.swing.JButton ShowBtn;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel Title1;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
